#!/usr/bin/env python3
"""Compose the canonical UR5e and Robotiq 2F-85 URDF descriptions.

The generated file deliberately contains no Berkeley TCP link.  The Berkeley
TCP is a dataset/task frame, while this file describes the physical assembly.
Keeping composition deterministic also lets tests prove that no UR5e link or
joint was edited while the gripper description evolves.
"""

from __future__ import annotations

import argparse
import copy
import difflib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = REPO_ROOT / "assets" / "robots" / "ur5e"
DEFAULT_ARM = ASSET_DIR / "ur5e_mesh.urdf"
DEFAULT_GRIPPER = ASSET_DIR / "robotiq_2f_85.urdf"
DEFAULT_OUTPUT = ASSET_DIR / "ur5e_robotiq_2f_85.urdf"

MOUNT_JOINT_NAME = "tool0_to_robotiq_arg2f_base_link"
MOUNT_PARENT = "tool0"
MOUNT_CHILD = "robotiq_arg2f_base_link"
MOUNT_XYZ = "0 0 0"
MOUNT_RPY = "0 0 1.5707963267948966"


def _parse(path: Path) -> ET.Element:
    root = ET.parse(path).getroot()
    if root.tag != "robot":
        raise ValueError(f"Expected <robot> root in {path}, got <{root.tag}>")
    return root


def _named(root: ET.Element, tag: str) -> dict[str, ET.Element]:
    result: dict[str, ET.Element] = {}
    for element in root.findall(tag):
        name = element.get("name")
        if not name:
            raise ValueError(f"Unnamed <{tag}> in robot {root.get('name')!r}")
        if name in result:
            raise ValueError(f"Duplicate <{tag}> name {name!r} in robot {root.get('name')!r}")
        result[name] = element
    return result


def compose(arm_path: Path, gripper_path: Path) -> ET.Element:
    arm = _parse(arm_path)
    gripper = _parse(gripper_path)

    arm_links = _named(arm, "link")
    gripper_links = _named(gripper, "link")
    overlap = sorted(arm_links.keys() & gripper_links.keys())
    if overlap:
        raise ValueError(f"Arm/gripper link names overlap: {overlap}")
    if MOUNT_PARENT not in arm_links:
        raise ValueError(f"Arm has no mount parent link {MOUNT_PARENT!r}")
    if MOUNT_CHILD not in gripper_links:
        raise ValueError(f"Gripper has no mount child link {MOUNT_CHILD!r}")

    arm_joints = _named(arm, "joint")
    gripper_joints = _named(gripper, "joint")
    joint_overlap = sorted(arm_joints.keys() & gripper_joints.keys())
    if joint_overlap or MOUNT_JOINT_NAME in arm_joints or MOUNT_JOINT_NAME in gripper_joints:
        raise ValueError(f"Arm/gripper joint names overlap: {joint_overlap}")

    output = ET.Element("robot", {"name": "ur5e_robotiq_2f_85"})
    output.append(
        ET.Comment(
            " GENERATED by scripts/build_ur5e_robotiq_2f85_urdf.py; edit the two canonical input URDFs instead. "
        )
    )

    # URDF parsers accept arbitrary child order, but grouping makes reviews and
    # semantic comparisons straightforward.
    for source in (arm, gripper):
        for element in source.findall("material"):
            output.append(copy.deepcopy(element))
    for source in (arm, gripper):
        for element in source.findall("link"):
            output.append(copy.deepcopy(element))
    for element in arm.findall("joint"):
        output.append(copy.deepcopy(element))

    mount = ET.SubElement(output, "joint", {"name": MOUNT_JOINT_NAME, "type": "fixed"})
    ET.SubElement(mount, "parent", {"link": MOUNT_PARENT})
    ET.SubElement(mount, "child", {"link": MOUNT_CHILD})
    ET.SubElement(mount, "origin", {"xyz": MOUNT_XYZ, "rpy": MOUNT_RPY})

    for element in gripper.findall("joint"):
        output.append(copy.deepcopy(element))

    ET.indent(output, space="  ")
    return output


def serialize(root: ET.Element) -> bytes:
    return ET.tostring(root, encoding="utf-8", xml_declaration=True, short_empty_elements=True) + b"\n"


def _diff(expected: bytes, actual: bytes, output_path: Path) -> str:
    return "".join(
        difflib.unified_diff(
            actual.decode().splitlines(keepends=True),
            expected.decode().splitlines(keepends=True),
            fromfile=str(output_path),
            tofile="generated",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arm", type=Path, default=DEFAULT_ARM)
    parser.add_argument("--gripper", type=Path, default=DEFAULT_GRIPPER)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if --output is absent or differs from deterministic composition.",
    )
    args = parser.parse_args()

    generated = serialize(compose(args.arm.resolve(), args.gripper.resolve()))
    output_path = args.output.resolve()
    if args.check:
        if not output_path.exists():
            print(f"Missing generated URDF: {output_path}", file=sys.stderr)
            return 1
        actual = output_path.read_bytes()
        if actual != generated:
            print(_diff(generated, actual, output_path), file=sys.stderr, end="")
            return 1
        print(f"up to date: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(generated)
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
